### ISSUE TITLE
Scalar vallue/infinite money bug

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#1]
when picking up money bags, a scalar value error might occur giving that player infinite money.

**Comment by JoSchaap** [comment]
This has been fixed in initial release, we will keep an eye out in case it re-appears again

**Comment by killernetworkgaming** [comment]
still buged some players get random inf money noticed if you go to put an item down and you stay on the invent page for a few mins the item is back in your inventory but also in the part to drop item

**Comment by JoSchaap** [comment]
duplicate of #8
