### ISSUE TITLE
Refuel error

### ISSUE THREAD

**Issue by Krunch** [JoSchaap/GoT_Wasteland_V2.Stratis#100]
There is an error showing when you try to refuel at an invalid location (a.k.a not next to a vehicle). Screen below for more details.

Steps to reproduce:
1. Get a jerry can
2. Open player menu
3. Try to use jerry can
...
4. Error!

![refuel](https://f.cloud.github.com/assets/1214548/897380/45b0701e-faf1-11e2-8f3b-a463766b01c5.png)

**Comment by JoSchaap** [comment]
70c286d6e54643c77b7de2c9e16281f3720d77a9
e5cef0a2b001e0555893b6f78b0524fc8c74f230
b68bf16fc950b5419528ea2ea50788397705abfe

fixed in v2.4
