### ISSUE TITLE
Make mission undependent of settings file

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#104]
Too many ppl are just grabbing the pbo without the antihack payload and settings file.

V2.3 will not load spawns and missions without it.

Make the mission default to daylight. Lootspawn. Without basesaving if the settingsfile is not found

**Comment by AgentRev** [comment]
Told you :wink:

**Comment by Solo-** [comment]
Yes, but that is how it always went and all of a sudden you have to grab the binary pbo and read all about it there, i always took right from the start page github

**Comment by Solo-** [comment]
after all it was the master

**Comment by JoSchaap** [comment]
A proper readme.md will be added on 2.4  :)
