### ISSUE TITLE
whats the directory path to the file i need to edit to change starting cash

### ISSUE THREAD

**Issue by ghost** [JoSchaap/GoT_Wasteland_V2.Stratis#107]

**Comment by ghost** [comment]
cant find it anywhere wtf am i blind

**Comment by JoSchaap** [comment]
it has moved abit to fix the huge amount of moneybags on the debug-island :)

here it is: https://github.com/JoSchaap/GoT_Wasteland_V2.Stratis/blob/master/client/functions/spawnAction.sqf#L11

i will look into making this configurable through the GoT_Settings.sqf for v2.4
