### ISSUE TITLE
Armed Diving Mission use wrong group

### ISSUE THREAD

**Issue by 82ndab-Bravo17** [JoSchaap/GoT_Wasteland_V2.Stratis#110]
The Armed diving expedition uses CivGrpS, but is a main mission. This causes it to interfere with the running side mission when started and removes all ai from the side mission.. Making all the CivGrpS and CivGrpM private seems to fix it, and will allow for multiple missions in the future. Or it could just be corrected to CivGrpM.

**Comment by JoSchaap** [comment]
both :)

should be M
but also should be private!

thanks!

**Comment by JoSchaap** [comment]
37ef9a6b5d40ccdfcc722d62ebb9715ff553d699
