### ISSUE TITLE
add new objects (spawnbeacon for example) to be filters

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#114]
drop spawn beacon..

BE kick xD

**Comment by SCETheFuzz** [comment]
Woot Battleye works still :D

**Comment by JoSchaap** [comment]
fixed https://github.com/JoSchaap/Arma3_Binary_PBO/blob/master/Sandbox56_GoT_Wasteland_V23_A3-Stratis/be-filters/createVehicle.txt
