### ISSUE TITLE
alter gunstore prices to reflect real life retail values

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#14]
This came in via a player as an idea.. and aside from to headackes finding all prices. he does have a point..

sofar he has found a website with prices on all scopes. ill doo some research myself ass-well :) 

optics (thanks Majestic!) -> http://www.opticsplanet.com/military-store.html

**Comment by AgentRev** [comment]
A GM6 Lynx costs about $15 000, and an M200 (M320 LRR), $11 000.
A TAR-21 (TRG-21) costs about $1500, and a Bushmaster ACR (MX), about $2500.
An RPG32 is about $2500, and an NLAW, $3000 (including one missile each).
Just saying.

**Comment by JoSchaap** [comment]
hmm maybe remove a decimal of retail, but still regarding the relation to eachother, researching the retail prices might still be a good idea to do :)

**Comment by JoSchaap** [comment]
chose not to go for full retail prices but did raise the prices in the gunstore and reduced the starting money :)
