### ISSUE TITLE
improvements for current betacontent

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#27]
```
 - The MK20s aren't in the gun store
 - The Vermin SBR is 9mm, not 45acp
 -
 -
 -
```

awaiting further player input :+1:

**Comment by ZoneTrooper** [comment]
So far so good,but with some vehicles i still have the issue that i have to enter driver seat and then i can pick up weapons,but its not with every vehicle in som cases i cam pick them up normaly.The Divers are nearly invulnerable you hit them from 4 meters away he doesnt die.

**Comment by JoSchaap** [comment]
vermin DOES use acp ammo (just confirmed this in the arma3 config viewer) 
MK20 will be added today

**Comment by JoSchaap** [comment]
oh this should not be closed as i want to use this issue for further communication about the beta content :)

new build is up with several fixes :)
