### ISSUE TITLE
remove time acceleration from beta branch

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#28]
tried different settings but even at 4x speed it causes problems and lag
going to remove it and when public go back to a day/night version of the mission

**Comment by nickludlam** [comment]
We tried that on our server too, but something about the weather calculations made it get progressively worse over time.

**Comment by JoSchaap** [comment]
yeah it was a nice plugin but it makes the clouds look like slideshows even at 2x (tested that too)
so i guess its byebye with the TimeXLR8 addon :)

**Comment by JoSchaap** [comment]
resolved in 32e0fdb4afd5860997baa1025095917d10caf306
