### ISSUE TITLE
remake base composition for outpost mission

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#29]
the old one just doesnt look right :)

**Comment by JoSchaap** [comment]
something like this :)
http://cloud-2.steampowered.com/ugc/595881303951290760/D48F0CB45DEE270C99E97E4DCB6883E2FCE8863E/

**Comment by nickludlam** [comment]
That sounds brilliant, but wouldn't base building depend on base persistence between reboots? Are you thinking of integrating the mechanics to iniDB? 

(also, I'd love to chat to you more about ArmA dev stuff. I work on the KoS Wasteland server. Is there a good forum in which we can chat? or is email better?)

**Comment by k4n30** [comment]
Maybe JoSchaap should make a skype group, it seems thats what all the other mods are doing

**Comment by JoSchaap** [comment]
@k4n30 im a 1 man team, so in order not to forget i have to keep anything i want to do/change in writing or it will end up in an empty void :)

i could make a new skype account for the got2dayz stuff, ive got some of you on steam but to be honest my first intention was on keeping steam to family and friends :)

ill see if i can create a skype account tonight so we can chat 

@nickludlam This is a mainmission, which despawns if the mission fails, if completed (all AI killed you can take the baseparts with you (bring a truck) and grab the ammocrates with special weapons and launchers :)

as far as iniDB, that question passes every day and in my opinion persitance is something the server admin should implement, as it requires only 1 line of code inside the missionfile, and the rest is a seperate mod, also storage for the data needs to be aranged.

personally im not a fan of persitant games, but i do want to improve the cleanup so servers kan stay up for 12hours without too much clutter

**Comment by JoSchaap** [comment]
oh and this issue has been partially resolved in 32e0fdb4afd5860997baa1025095917d10caf306
i might make a second composition later
