### ISSUE TITLE
all vehicles marked as hacked vehicles (no owner)

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#31]
since moving the keygen file, probably missed something somewhere..

**Comment by AgentRev** [comment]
I'll check your code in a couple hours.

**Comment by AgentRev** [comment]
You should update the following files from my master:

```
client\systems\adminPanel\findHackedVehicles.sqf
server\functions\checkHackedVehicles.sqf
server\functions\findClientPlayer.sqf
server\functions\fn_vehicleInit.sqf
```

Then, remove the following code from your root "init.sqf":

```
vChecksum = 1;

{
    vChecksum = vChecksum + _x;
} forEach (toArray versionName); 
```

After that, remove the following line from "server\functions\serverCompile.sqf", and add it instead under "generateKey = ..." in your root "init.sqf":

```
fn_vehicleInit = compile preprocessFileLineNumbers "server\functions\fn_vehicleInit.sqf";
```

**Comment by JoSchaap** [comment]
Appreciated! On a train now so I'll get this done later :)

**Comment by AgentRev** [comment]
Also, if you spawn a motorized vehicle from the client without assigning it the vChecksum, or spawn any ammo crate from the client, it will show up in the hacked vehicles.

"Unknown owner" means no one has entered the vehicle since it spawned, or that the last driver disconnected from the server.

**Comment by JoSchaap** [comment]
thanks! 

8e3929e0d5ae6715033e85bfdc25ebf033f18420
