### ISSUE TITLE
hunt down incorrect calls to FindSafePos

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#35]
theres an ammount of RPT spam again, going to make a debug version on my servers that log the calls to FindSafePos so i can find the cullprit

```
  if (!((count (_testPos isFlatEmpty [_objDist, 0, _maxGradient, >
    Error position: <isFlatEmpty [_objDist, 0, _maxGradient, >
    Error Type Any, expected Number
  File A3\functions_f\misc\fn_findSafePos.sqf, line 100
```

**Comment by JoSchaap** [comment]
think i found it: 

```
   GOOD: "--DEBUG-- [vehicleCreation] call findsafepos with args: [[2058.42,5361.66,0], 1, 35, 5, 0, 60 * (pi / 180), 0, [], [[2058.42,5361.66,0]]] --DEBUG--"
    BAD: "--DEBUG-- [vehicleCreation] call findsafepos with args: [[4016.54,7957.42,0], 1, 35, any, 0, 60 * (pi / 180), 0, [], [[4016.54,7957.42,0]]] --DEBUG--"
```

e9a425fba36ef4964a94a3971ec23ae25f66400f

implemented on both servers, lets see :)

**Comment by JoSchaap** [comment]
nope.. still happenning.. 

```
   bad: "--DEBUG-- [vehicleCreation] call findsafepos with args: [[4295.51,2688.2,0], 1, 35, any, 0, 60 * (pi / 180), 0, [], [[4295.51,2688.2,0]]] --DEBUG--"

  good: "--DEBUG-- [vehicleCreation] call findsafepos with args: [[4295.51,2688.2,0], 1, 35, 5, 0, 60 * (pi / 180), 0, [], [[4295.51,2688.2,0]]] --DEBUG--"
```

seems like the vehicle respawn is creating a vehicle it cannot determine a type number for..

if al alse fails ill add a bandage to the any value :/

**Comment by AgentRev** [comment]
This is kinda puzzling... No matter how I look at this bug, I am still confused. The only reason I can think of is that `_type` might be undefined under certain conditions when `BIS_fnc_findSafePos` is being called... You might wanna add the value of `_cartype` and `_type` in the debug line to check.

But, I know for sure that this last commit of yours will not fix the bug. It will only create more errors, as `vehicleSpawning` only passes one argument to `vehicleCreation`. That's the reason why I had placed `_cartype = _this select 1` inside the `if (count _this > 1)`

**Comment by AgentRev** [comment]
Another thing you could try, in `server\functions\vehicle.sqf` at line 165, change the `if (_cartype ...` to `if (_carType ...`

I don't know if private variables are case sensitive, but if they are, this could surely be causing the bug.

**Comment by JoSchaap** [comment]
it goes well during initial spawn, but wrong during respawn

**Comment by AgentRev** [comment]
Yeah, try to add `_cartype` and `_type` to the debug, that should give us a lead.

**Comment by JoSchaap** [comment]
ill add it but cant update the servers untill one of them goes empty :+1: 
probably tomorrow 

8a55014713f2425b5bf15203524b43558521c25c

**Comment by JoSchaap** [comment]
ok implemented on both servers #nowwewait :)

**Comment by JoSchaap** [comment]
Aint much help but atleast we know the vehicles now :)

bad:

```
  "--DEBUG-- [vehicleCreation] call findsafepos for(C_Offroad_01_F type:any) with args: [[4016.54,7957.42,0], 1, 35, any, 0, 60 * (pi / 180), 0, [], [[4016.54,7957.42,0]]] --DEBUG--"
```

few mins later another one went well:

```
  "--DEBUG-- [vehicleCreation] call findsafepos for(C_Quadbike_01_F type:0) with args: [[4295.51,2688.2,0], 1, 35, 5, 0, 60 * (pi / 180), 0, [], [[4295.51,2688.2,0]]] --DEBUG--"
```

then a little later it went wrong again:

```
  "--DEBUG-- [vehicleCreation] call findsafepos for(I_Truck_02_covered_F type:any) with args: [[1856.35,5510.07,0], 1, 35, any, 0, 60 * (pi / 180), 0, [], [[1856.35,5510.07,0]]] --DEBUG--"
```

right after that one wen well and another one failed :/

```
  "--DEBUG-- [vehicleCreation] call findsafepos for(O_Quadbike_01_F type:1) with args: [[1659.63,5022.32,0], 1, 35, 2, 0, 60 * (pi / 180), 0, [], [[1659.63,5022.32,0]]] --DEBUG--"
```

Behaviour

```
    "--DEBUG-- [vehicleCreation] call findsafepos for(C_Offroad_01_F type:any) with args: [[3235.3,5864.46,0], 1, 35, any, 0, 60 * (pi / 180), 0, [], [[3235.3,5864.46,0]]] --DEBUG--"


  "--DEBUG-- [vehicleCreation] call findsafepos for(C_Offroad_01_F type:any) with args: [[4016.54,7957.42,0], 1, 35, any, 0, 60 * (pi / 180), 0, [], [[4016.54,7957.42,0]]] --DEBUG--"
```

this is puzzing :/  seems the offroad and truck are being affected most :/

**Comment by JoSchaap** [comment]
oh wait

it might be because of case sensitivity in the servervars file  i had different caps on these 2 vehicles... :/
attempt to fix this in a minute

72951951144626590740a923977754bf750cf7a5

**Comment by AgentRev** [comment]
That's exactly what I was about to say. From http://community.bistudio.com/wiki/in_Array :

`If x is a string, the array is checked case-sensitive`

Hence why I always copy and paste class names from the config viewer.

**Comment by JoSchaap** [comment]
and yet it's quite satisfying to learn like this :) :!

**Comment by JoSchaap** [comment]
keep pusing the close button for some reason xD

**Comment by AgentRev** [comment]
Me too, it's not well placed. I keep mistaking it for a button to close the comment form, not the issue.

**Comment by AgentRev** [comment]
Also, unrelated, but you should remove the civi quadbike from `civilanVehicles`, and put it with the other quads in `lightMilitaryVehicles` instead, because it effectively changed spawning odds from 30% offroads / 45% quadbikes to 15% offroads / 60% quadbikes.

**Comment by JoSchaap** [comment]
now that you mention it, great idea, i was wonderring where all the damn quads kept comming from :)

**Comment by JoSchaap** [comment]
seems to be fixed but ill give it another night

**Comment by JoSchaap** [comment]
fixed, problem was caused due to case sensitive classnames..

https://github.com/JoSchaap/GoT_Wasteland_V2.Stratis/pull/42
