### ISSUE TITLE
enable transport on speedboat from armed diving expedition

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#38]
players should be able to put the crates in it :)

**Comment by AgentRev** [comment]
Isn't it supposed to enable automatically, as long as the vehicle type is specified in R3F's config?

**Comment by JoSchaap** [comment]
for some reason mission vehicles dont have r3f enabled, but it isnt that hard to enable this in the missionfile ;)
https://github.com/JoSchaap/GoT_Wasteland_V2.Stratis/blob/%23TEMP_DEBUGBRANCH_V221/server/missions/mainMissions/mission_ArmedDiversquad.sqf#L62

will be/is allready  fixed in v2.21
9c8f8f7b8a8f3bbb2b3147dec3652f15ac25f2ea
