### ISSUE TITLE
Credit for original anti-hack

### ISSUE THREAD

**Issue by matsuiman** [JoSchaap/GoT_Wasteland_V2.Stratis#39]
Hey there, I just want to say that I'm the original creator of the script you based your anti-hack off. It's totally ok that you use it (you redid almost the whole thing so yeah), but it would be nice with some credits.

Here's some "proof" that it was me who made it:
A link to a previous version (for DayZ), you can clearly see that it has the same diag_log messages (just that somebody removed my name):
http://www.opendayz.net/threads/new-version-of-anti-cheat-script.7229/
http://www.mediafire.com/view/y0490oqnpscfn47/antihack.sqf
I later on ported the script over to ArmA III when the alpha came out.

I'd like to be credited as AWA.

**Comment by JoSchaap** [comment]
nice timing! 

Just yesterday I was talking about this with @AgentREV, and he got it from SPJESTER who got it from 'some dayz mission file'. thats as far as we could trace it back :+1: 

Absolutely no problem in adding you into the credits (will be from 2.21 and upwards)

**Comment by JoSchaap** [comment]
will be fixed in v2.21
6b6c93b8e3c0e375a8b4aca830cfb9cd1554ff22

**Comment by matsuiman** [comment]
Thank you! :+1:

**Comment by AgentRev** [comment]
Thanks for the heads up, I did try to search for the author when I got it, but I couldn't find anything relevant. Will also fix in my version.
