### ISSUE TITLE
Wasteland ending with "Mission Failed"

### ISSUE THREAD

**Issue by s3kShUn61** [JoSchaap/GoT_Wasteland_V2.Stratis#49]
JoSchaap you were in my server when the glitch happened. It was happening since the beta release version of GoT Wasteland. I unfortunately have only been in the server once when this has happened so I don't have anymore information on it.

**Comment by JoSchaap** [comment]
Hi!

You are probably referring too the 'mission failed. All players died' bug. This is affecting all servers on stable branch at this moment. Also triggerred if a hacker kills all players. In the dev branch this has been fixed. And i'm hoping that bis will update the stable branch again verry soon. Untill then it's not something that van be fixed from within the mission.

v2.3 is currently being tested and expanded on our servers of the dev branch of arma3
