### ISSUE TITLE
Gunstore *lag* purchase glitch

### ISSUE THREAD

**Issue by s3kShUn61** [JoSchaap/GoT_Wasteland_V2.Stratis#50]
Currently in gunstores if a player adds say 5 mags to their cart, then spams purchase (assuming they have enough money for the 5 mags), it will give them 5xHowever many times they pressed purchase mags while only charging them for the initial 5. This grows exponentially with lag in the server. I was thinking of fixing it by subtracting the cost of the mags from the player's money immediately upon placement however addToCart.sqf would need to be modified so that the individual items price can be deducted immediately upon placing it in the player's inventory. The only other solution which I do not know how to do would be to disable the purchase button immediately after the first press for about a sec or so for the lag to catch up.

**Comment by JoSchaap** [comment]
or just add a check to the button to re-check the money the player has :+1: 

thanks for reporting this

**Comment by s3kShUn61** [comment]
Didnt know you could do that lol. Still learning all the arma coding stuff

**Comment by JoSchaap** [comment]
Please keep issues open so i dont forget to implement them ;)

**Comment by JoSchaap** [comment]
fixed in v2.3
