### ISSUE TITLE
(antihax:update) implement latest version by @AgentREV

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#51]
note to self: send this person a random gift on steam :)

**Comment by JoSchaap** [comment]
note to self: executed :+1: 

will today bring us battleye? :+1:

**Comment by s3kShUn61** [comment]
We can only hope!

**Comment by AgentRev** [comment]
Thanks for the gift man, that's really appreciated. I haven't had much time during the last days, but I'll try to complete my latest revision tomorrow, and pass you the antihack along. Can't wait for BattlEye.

**Comment by JoSchaap** [comment]
Not a problem. Devbranch is broken today Anyway! 

Cvg-rifles no longer works :)

**Comment by JoSchaap** [comment]
implemented

https://github.com/JoSchaap/GoT_Wasteland_V2.Stratis/commit/29c9f81dd2b27500e8a91bbf57b64d443f263073

thanks alot to @AgentRev  and Tonic :+1:
