### ISSUE TITLE
Hilarious Convoy Glitch

### ISSUE THREAD

**Issue by s3kShUn61** [JoSchaap/GoT_Wasteland_V2.Stratis#52]
So the NPC convoy mission with the HMG Strider has one of the best glitches I've ever seen. I ran to the side of the Strider with 3 NPCs inside, one driving, one gunning, and one passenger. I then was able to get in with them and it moved them to the next empty seat if I were to try and switch to a currently occupied seat. I was able to gun with the NPC driving then switch to driver and the NPC would shoot people! Then later when I was gunning I guess the NPCs finally had enough of me and hopped out. I shot and killed all three with the Strider HMG which then led to another glitch, there was a no name on the leaderboards with 3 kills. That was from me killing them with the mission vehicle while it was still registering as an NPC controlled vehicle. I do have video of it if you would like me to post it as well.

**Comment by JoSchaap** [comment]
thanks for reporting will work on either a lock on the vehicles :)

**Comment by JoSchaap** [comment]
fixed inn: 2b4a01b009ee8b005af7493138cb491574af06f7
