### ISSUE TITLE
fix the mission..

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#53]
went abit overboard updating provinggrounds fpr v2.3. current mission state = FUBAR
will fix it but i got a family too xD

**Comment by JoSchaap** [comment]
all of todays updates have been reverted. the new provinggrounds will be a future idea. not for v2.3

**Comment by JoSchaap** [comment]
ok it is the dev branch itself thats broken today CVG_Rifles is no longer here.. _bangs head to desk_

ahwell server downgraded to stable and will try again tomorrow!

**Comment by AgentRev** [comment]
I checked both our masters, and the CVG variables are never even used.

**Comment by JoSchaap** [comment]
its in function > servervars :)

but it has been fixed allready :)

the only thing that doesnt work on DEV branch is the respawn dialog. no idea why...

**Comment by AgentRev** [comment]
Yes they are declared in serverVars, but they are not actually used anywhere.

**Comment by JoSchaap** [comment]
lol xD

ahwell there is a more serious flaw in dev atm pettka will be looking into it tomorrow
http://forums.bistudio.com/showthread.php?152866-Development-branch-discussion&p=2439279&viewfull=1#post2439279

**Comment by JoSchaap** [comment]
bis and dayz forums where hacked.. this will be continued after they fix the forums :)

**Comment by JoSchaap** [comment]
seems to be fixed, although im sticking to the stable branch untill we have the forums back :1
