### ISSUE TITLE
Gunstore menu

### ISSUE THREAD

**Issue by s3kShUn61** [JoSchaap/GoT_Wasteland_V2.Stratis#58]
When a player is killed while in the gunstore menu, on respawn they are still in the menu and able to purchase items.

On another note, Jo I sent you a message on reddit.

**Comment by JoSchaap** [comment]
ill add a CloseDialog xD

**Comment by JoSchaap** [comment]
should be fixed with: 22cdabf5e3fb3e204bcaa78d9c01ac156b8169a2
