### ISSUE TITLE
(Devbranch:Anticheat) Create battleye filters for wasteland (scripts.txt)

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#64]
Since DEV has battleye, might asswell look into this ass-well

**Comment by AgentRev** [comment]
Yep, will have to look into this with you. My new anti-hack will still have some use, since it filters out character patterns  used to bypass BattlEye, like `create""+""Vehicle`.

Those will definitely be useful as a reference:
http://dayz.st/w/Battleye_Filters
https://github.com/DayZMod/Battleye-Filters

**Comment by JoSchaap** [comment]
_note_ make sure the filters dont trigger antihax and vice-versa :)

**Comment by AgentRev** [comment]
My `createVehicle.txt` filter will be quite simple:

```
5 ""
```

**Comment by JoSchaap** [comment]
doesnt the client create the bag with money upon death? :)

**Comment by AgentRev** [comment]
Oh, you're right. I guess I would've figured out the hard way.

**Comment by AgentRev** [comment]
I just wish there would be a way to simply block vehicles of types "AllVehicles" & "ReammoBox_F", and allow the rest.

**Comment by AgentRev** [comment]
Here's my `createVehicle.txt` so far :

```
5 "" !"GroundWeaponHolder" !"Supply" !"B_Kitbag_" !"B_Bergen_" !"B_Carryall_" !"Land_Sacks_F" 
```

**Comment by AgentRev** [comment]
Updated :

```
5 "" !"GroundWeaponHolder" !"Supply" !"B_Kitbag_" !"B_Bergen_" !"B_Carryall_" !"B_AssaultPack_" !"B_FieldPack_" !"B_Parachute" !"Land_Sack_F" !"_medic_F" !"_soldier_repair_F" !"_soldier_exp_F" 
```

**Comment by AgentRev** [comment]
Meh I think it will be easier to just list the vehicles to kick for instead, because every rocket is considered a vehicle...

**Comment by SCETheFuzz** [comment]
I'm reworking some of my filters from dayz. I wil pass off what I get done Rev think it would be nice to be able to hand out battleye filters with the mission for servers.  <Code> addbackpackcargo.txt </Code>

<code> 1 "" !"B_Kitbag_Base" !"B_Parachute" </code> 

Keeping it at 1 until i get a few more hours of play time and players in the server.

**Comment by AgentRev** [comment]
Here's my new `createVehicle.txt` :

```
// Vehicles
5 "_APC_"
5 "_Boat_"
5 "_Heli_"
5 "_Lifeboat"
5 "_Mortar_"
5 "_MRAP_"
5 "_Offroad_"
5 "_Quadbike_"
5 "_Rubberboat"
5 "_SDV_"
5 "_Truck_"

// Ammo boxes
5 "Box_"
5 "_supplyCrate_"

// Units
5 "C_man_"

// Buildings & objects
5 "Bomb"
5 "Land_" !"Land_Sack_F" !"Land_Basket_F" !"Land_Bucket_F" !"Land_Suitcase_F" !"Land_CanisterFuel_F"
```

**Comment by JoSchaap** [comment]
add these ignores to the buildings  (land_) too

!"Land_Basket_F" !"Land_Bucket_F" !"Land_Suitcase_F" !"Land_CanisterFuel_F"

they are generated by: 
https://github.com/JoSchaap/GoT_Wasteland_V2.Stratis/blob/%23TEMP_TESTING_V23/client/clientEvents/onKilled.sqf

**Comment by JoSchaap** [comment]
easyest way to find out about client generated vehicles is just using a search tool such as Agent Ransack on the client folder searching for "createvehicle"

**Comment by JoSchaap** [comment]
and disallow creation of "Bomb" :)

**Comment by AgentRev** [comment]
Is "Bomb" used by any weapon/vehicle?

**Comment by JoSchaap** [comment]
no but its an actual bomb that can be set off by schooting at it and should not be in the game :D

try it ingame but turn down your volume before shooting at it :D

**Comment by JoSchaap** [comment]
we should also allow

"Land_cargo_addon02_V2_F"

since its the placeholder for the camonet system (Improvised roof)
