### ISSUE TITLE
(DEV:New content) SMG optics, and 2 new tracked APC's

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#67]
Seperate DEV BRANCH - SubBranch for DEVbranch users only

**Comment by JoSchaap** [comment]
added to TEMP_DEVBRANCHONLY_V23

https://github.com/JoSchaap/GoT_Wasteland_V2.Stratis/commit/bd0736631bd56164309cba562865452d42f0c09c

**Comment by AgentRev** [comment]
Think you could grab a screenshot of the APCs?

**Comment by JoSchaap** [comment]
http://imgur.com/a/ryE7e

**Comment by AgentRev** [comment]
Very nice, thanks.
