### ISSUE TITLE
alot of errors on dev branch

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#68]
lets hope either bis get's their debugging straight or i learn how to declare variables properly atm for DEV the mission is FUBAR

**Comment by JoSchaap** [comment]
first attempt in fixing this is in:
d16ebc7e168cfa0797bf0019e0497af95115c3f1

**Comment by JoSchaap** [comment]
first tester says it seems fixed :+1: 

need to confirm myself tonight, both servers updated and running this on latest DEV branch :)

[NL] GoT Wasteland v2.3(test) #1 [NIGHT/BaseSaving] [VETERAN/3RDP:ON/VON:ON]
[NL] GoT Wasteland v2.3(test) #2 [DAY/BaseSaving] [VETERAN/3RDP:ON/VON:ON]

**Comment by JoSchaap** [comment]
just need to fix the deletevehicle function being an ass :)

15:18:58 Error in expression <ed
};

if(_failed) then
{

if not(isNil _vehicle) then {deleteVehicle _vehicle;}>
15:18:58   Error position: <_vehicle) then {deleteVehicle _vehicle;}>
15:18:58   Error Undefined variable in expression: _vehicle
15:18:58 File mpmissions__cur_mp.Stratis\server\missions\sideMissions\mission_HostileHelicopter.sqf, line 110

**Comment by AgentRev** [comment]
You forgot quotes: `not(isNil "_vehicle")`

And looking at the file, `_vehicle` will always be nil, because it doesn't seem to be assigned anywhere in the same locality as your `not isNil` condition.

**Comment by JoSchaap** [comment]
oh wow.. thats just..  _slaps forhead_

gotta love scripting... where every character counts :+1:

**Comment by JoSchaap** [comment]
abfdf4ede98627f1d0e1155e34bf573eea6b4659
