### ISSUE TITLE
Helicopter Missions - Helos dont take fuel

### ISSUE THREAD

**Issue by s3kShUn61** [JoSchaap/GoT_Wasteland_V2.Stratis#70]
Title is self explanatory. I have not seen this myself as I have been away for the past few days but my admins tell me that most if not all of the helicopters from the helo missions cannot take fuel and are rendered useless.

**Comment by AgentRev** [comment]
From pumps or jerry cans?

**Comment by JoSchaap** [comment]
they can but their 'sweetspot' for refuelling is hard to find.
the refuel system has been changed too since it still had some deprecated code in it :)
you do have to use fuelcans on most heli's though. the autorefuel does not work on most of them
