### ISSUE TITLE
R3F is disabled for non-Building objects when joining

### ISSUE THREAD

**Issue by AgentRev** [JoSchaap/GoT_Wasteland_V2.Stratis#79]
See AgentRev/Arma3-404Wasteland-Stratis-TPG@8213aad9ff9b9333dd6ca65cd18eeb4fcf4c55c4

Basically, just change `allMissionObjects "Building"` to `allMissionObjects "All"` in your init script.

If you only skip "Building" objects, it also disables R3F for anything else that isn't a building, like crates and sacks. This mainly affects players who join after objects have spawned on the server.

**Comment by JoSchaap** [comment]
thanks

f0bf21b534d9e08d51f38403ae77f76d914470b2
bba03435ff6dbf5d4efa7b6a57c4f1f0007424b1
