### ISSUE TITLE
rename mission pbo filename (community request) and distributionmethod of release

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#81]
http://forums.bistudio.com/showthread.php?159890-Missions-File-Name-Insufficient-to-help-user-finding-what-he-wants

mission will be available in 4 flavours renamed to:

Daytime version (basesaving:on) Sandbox65_@inidb_GoT_Wasteland_v23_day.Stratis.pbo
Nighttime version (basesaving:on) Sandbox65_@inidb_GoT_Wasteland_v23_night.Stratis.pbo
Daytime version (basesaving:off) Sandbox65_GoT_Wasteland_v23_day.Stratis.pbo
Nighttime version (basesaving:off) Sandbox65_GoT_Wasteland_v23_night.Stratis.pbo

Each version of the mission will be packaged as a zipfile to include the serversided files needed for the antihack

**Comment by AgentRev** [comment]
Why don't you just add an external settings file with parameters to set daytime and basesaving? Some file like `GoT_Wasteland_Settings.sqf` to be added in the main ARMA 3 folder like the anti-hack:

```
// GoT Wasteland Settings

GoT_nightTime = 0; // set to 1 to have the mission start on evening instead of morning
GoT_baseSaving = 0; // set to 1 to enable base-saving (iniDB addon required)
PDB_ServerID = "one"; // iniDB prefix for base filenames - if running multiple servers, set a different value for each one!
```

Then, in your `server\init.sqf`, just after the "Server Compile Finished", add:

```
if (loadFile "GoT_Wasteland_Settings.sqf" != "") then
{
    call compile preprocessFileLineNumbers "GoT_Wasteland_Settings.sqf";
};

if (!isNil "GoT_nightTime" && {GoT_nightTime > 0}) then
{
    setDate [date select 0, date select 1, date select 2, 21, 0];
};

if (!isNil "GoT_baseSaving" && {GoT_baseSaving > 0}) then
{
    diag_log "GoT Wasteland - Initializing base-saving";
    execVM "persistentscripts\init.sqf";
};
```

**Comment by JoSchaap** [comment]
was thinking of doing this indeed :)

but im merely stating the mission naming convention :)

**Comment by AgentRev** [comment]
Yeah but with a settings file, you'd only need a single PBO.

**Comment by JoSchaap** [comment]
the time-thing is new to me so thanks for pointing that one out :)
ill definately go for that :)

**Comment by JoSchaap** [comment]
ok will be one file with an external settingsfile to define:
- day or night
- loot in buildings
- basesaving
- inidb prefix

Sandbox65_GoT_Wasteland_v23.Stratis.pbo

Everything will be nicely packaged in a zipfile
