### ISSUE TITLE
DEV branch debug messages (errorspam) now also on stable..

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#82]
yea great, now the mission is even unplayable on stable branch..

anyone got an idea how to disable the diag window on all clients?

its complaining about undeclared variables that are declared or sometimes even arent variables at all..

allready added !isnill checks to all of them last week, kinda wondering if im missing a mistake here or its just the game being an ass,,

code: https://github.com/JoSchaap/GoT_Wasteland_V2.Stratis/blob/%23TEMP_TESTING_V23/client/functions/newPlayerIcons.sqf#L121

error:
![wlerrorwtf](https://f.cloud.github.com/assets/2301588/858401/8c08bb70-f565-11e2-9141-b8cd196ba415.jpg)

**Comment by MercyfulFate** [comment]
I'm doing more extensive testing, but I still have no issues (with either my inventory system, nor the rest of wasteland). with that said, I have no serverRules.sqf (its just a straight checkout from your repo, no packaging into a pbo).

**Comment by JoSchaap** [comment]
that snuck in there when grabbing agentrevs new antihack :) its a file that should be placed outside the pbo :package: 

but these errors are annoying as fck :/

**Comment by JoSchaap** [comment]
there will be a few files that go into the server main folder (not in the mission)
- GoT_Settings
- antihax\payloadfiles
