### ISSUE TITLE
Build live - Need testers :)

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#84]
both servers have been updated on stable branch.

sadly i have a long day at work so it would be nice if some of you could join and test :)

servernames are:

```
   [NL] GoT Wasteland v2.3 #2 [DAY/BaseSave/ANTIHACK]
   [NL] GoT Wasteland v2.3 #1 [NIGHT/BaseSave/ANTIHACK]
```

hosted on stable branch!

password to join is:  

```
      borrelnoot
```

just post any error screenshots or issues here and i will look into it tonight

**Comment by EPM-Cortez** [comment]
Just joined and seems to be running fine, though all of a sudden the server went down. Not sure if that was you or caused by a script error.

**Comment by JoSchaap** [comment]
all our servers restart at 5 and 17:00 which was now ;)

also fixed a minor bug during the scheduled restart

**Comment by EPM-Cortez** [comment]
I'll join back in now and give it another test. Do you have an eta on the release?

**Comment by s3kShUn61** [comment]
Yea any release eta? I'd love to get rid of all these error messages on my clients screens

**Comment by JoSchaap** [comment]
thanks alot all for helping me test, i got a nice list off issues and a bucket full of black error dialog screenshots to to through. :)

two fixes have allready been deployed and the rest is on my list,

due to some unfortunate personal/family circumstances i cannot pull an allnighter right now to get the release out. Also I dont want to rush things. and get it done right this time..

**Comment by JoSchaap** [comment]
thanks for testing everyone, results and tofix/todo list and some screenshots in:
 #85
