### ISSUE TITLE
Create Readme.MD, explain configs, add BE Filters

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#89]
Create/update readme
maybe create a new introduction video? :)

**Comment by AgentRev** [comment]
Here's what I wrote in my readme:

> For BattleEye, please put the .TXT filters from the BattlEye folder of this archive in the BattlEye folder of your server, which is located where your .RPT log files are at.
> 
> By default, this folder should be at "%LocalAppData%\Arma 3\BattlEye", or in the folder defined by the "-profiles" options of your arma3server.exe shortcut.
> 
> If you are unsure, simply add "-BEPath=BattlEye" to your arma3server.exe shortcut, and place the .TXT files in the BattlEye folder where arma3server.exe is located.
> 
> It is recommended to only use the filters provided with this mission, as those from other sources may cause false positives.

**Comment by JoSchaap** [comment]
well github is taking a piss on the readme..

its done for now
