### ISSUE TITLE
disable player movement when using a store

### ISSUE THREAD

**Issue by JoSchaap** [JoSchaap/GoT_Wasteland_V2.Stratis#90]
right now players can open the store dialog and move on.
ill make it so players cant move while having the gunstore dialog openned

**Comment by JoSchaap** [comment]
```
  if (dialog) then 
  { 
     player enablesimulation false; 
  } else { 
     player enablesimulation true; 
  };
```

Now to find a nice place for it :+1:

**Comment by JoSchaap** [comment]
could not replicate

**Comment by AgentRev** [comment]
I still use the old gunstore, and I can't move either while it's open. @s3kShUn61, could you be more precise?
