### ISSUE TITLE
Errors in admin menu

### ISSUE THREAD

**Issue by s3kShUn61** [JoSchaap/GoT_Wasteland_V2.Stratis#92]
Create vehicle? Is this permanently disabled?
Also  I have two errors:
1..When I try to spectate any player I get this error message
http://i.imgur.com/DJmvRty.jpg

2..When trying to view any vehicles I get this:
http://i.imgur.com/u593RwY.jpg

**Comment by s3kShUn61** [comment]
Actually a ton of errors?? Cannot pickup money - get an error

**Comment by JoSchaap** [comment]
should all be hotfixed now
