### ISSUE TITLE
Errors in admin menu

### ISSUE THREAD

**Issue by s3kShUn61** [JoSchaap/GoT_Wasteland_V2.Stratis#93]
Create vehicle? Is this permanently disabled?
Also I have two errors:
1..When I try to spectate any player I get this error message
http://i.imgur.com/DJmvRty.jpg

2..When trying to view any vehicles I get this:
http://i.imgur.com/u593RwY.jpg

**Comment by s3kShUn61** [comment]
cannot pickup money - get an error

**Comment by MercyfulFate** [comment]
might be worth noting that if someone uses the "test function" option in the debug panel of the admin menu, they will get kicked by your battle-eye filters. not that its a massive problem.

**Comment by s3kShUn61** [comment]
There are a ton of problems right now. Where is Jo?

**Comment by s3kShUn61** [comment]
I cant even run the new binary mission. See my issues with screenshots in the V2 page.

**Comment by AgentRev** [comment]
Jo is asleep because it's 5:30 am where he lives.

**Comment by s3kShUn61** [comment]
Okay I realized that shortly after posting that. I found a problem in the binary download where there are two different versions of the pbo. Also, the image I included in my latest issue in the master branch is still occurring on the stable build of the mission.

**Comment by s3kShUn61** [comment]
@AgentRev , how can we tell if the filters are in the correct directory? I have a few BattlEye directories and tried each one on a new launch of the server with the filters in it and see no change in anything in the server. Namely we cannot spawn vehicles even without the filters, which Jo said if removed, would allow admins to spawn vehicles.

**Comment by JoSchaap** [comment]
could you guys stop the chaotic 'commenting everywhere' please :) this issue was closed after fixing the errors in the opening message :)

just add some offtopic info, i live in holland so yea it was past 4am when i was doing these  hotfixes and now im at work at 8 am till 19 pm at 22pm i need to start packing for our vaction weekend :)

**Comment by s3kShUn61** [comment]
@JoSchaap My apologies for the chaotic posting lol. I made the post twice and screwed it up.
