### ISSUE TITLE
Um we cannot access anything in vehicles and some vehicles spawn flying?

### ISSUE THREAD

**Issue by s3kShUn61** [JoSchaap/GoT_Wasteland_V2.Stratis#94]
Title...

**Comment by s3kShUn61** [comment]
Okay now we can. the server took like 5 mins then super lag and now items are duplicating

**Comment by s3kShUn61** [comment]
Jo whats going on? Now the mission wont even start... getting the weirdest error messages: http://i.imgur.com/2VNdrnp.png

**Comment by s3kShUn61** [comment]
Looks like an issue in the PBO? Looking into it now but looking at the two different pbos; the one located in the zipped folder is NEWER than the one located in the root/mpmission folder. And that one is missing server/init.sqf I believe.

**Comment by JoSchaap** [comment]
github seems to be messing up all the files bigtime..
next time ill just resort to a normal ZIPfile download :/

LOL if i compare #master to #temp_v23_test it pretends master is still at v2.21 :/
github is having some storage/caching issues...

nearly all old bugs are back :/

ill have a peek at everything in between jobs
