### ISSUE TITLE
List of minor issues

### ISSUE THREAD

**Issue by s3kShUn61** [JoSchaap/GoT_Wasteland_V2.Stratis#95]
-Medkits are not in general store
-Gunstore (&generalstore?) building are not indestructible (Able to drive through airbase gunstore after it is destroyed but AI will not move XD)
-Group management is still broken, it said invite from 'any' and then got an error message when I tried to accept it. I did not get a screenshot intime.
-Group management cannot be closed with 'esc' (very minor bug)
-Gunstores take money when trying to purchase when the player has a full inventory, does not say "No inventory space"
-Base saving not working? (This could be a problem with mine however. I am running the mod, it's listed in the server browser, and it is enabled in your config file)
-I will list more as we find them!

---All these bugs are with the pbo in the zipped folder from the binary download, not the one in the sandbox.../mpmissions folder in the root directory. That one appears to be an older version from yesterday and the one in the zip folder is from today.

**Comment by JoSchaap** [comment]
The first things are just working as i intended it.
Medkits are in te gunstore. And i never said i woukd.make buildings invulnerable. Just prevent the store from being moved.

Groups should. Work. We've even tested it. Will need more info on that (screen/log)

Gunstore.should check remaining space indeed. Will look at that. 

Today is my last day at work before a long weekend vacation. If i cant get it fixed ill nuke this release and start ook ver in tuesday

**Comment by MercyfulFate** [comment]
Did you want some help squashing bugs? I've got quite a few free hours I can dedicate if you want.

**Comment by JoSchaap** [comment]
First i need to get a hand on why github is trolling this release  :)

somehow files got reverted to older versions while merging them into master :/

**Comment by MercyfulFate** [comment]
I've just checked out your codebase in a clean environment and git refuses to switch between branches... something funny is going on for sure. let me know when you want me to help.

Don't know what you have done with git, but I cant fault you for doing it well!

**Comment by JoSchaap** [comment]
@MercyfulFate some players testing current bugs on my servers would be appreciated. i think i got the kinks out now :)
