### ISSUE TITLE
No Missions or spawning

### ISSUE THREAD

**Issue by Solo-** [JoSchaap/GoT_Wasteland_V2.Stratis#97]
Hi,

I have pulled of the master on the github and loaded onto my server but I have no missions or spawning in loot/vehicles. Is there something I must do in order to get those or is it completely broken now?

**Comment by Solo-** [comment]
Additional info:

64 slots
Connection Info:    188.94.75.217:2462
BE Enabled
Stable Branch

**Comment by JoSchaap** [comment]
you need the full package or the server sided stuff will not load :) grab it from the binary repo :)
https://github.com/JoSchaap/Arma3_Binary_PBO
just the PBO will no longer suffice due to the settings being outside the mission pbo now :)

**Comment by AgentRev** [comment]
You should make it so that the mission can run without settings files, at least that's what I've done for mine. Not all server owners look at the logs for error messages.

**Comment by Solo-** [comment]
Also, this server, I have iniDB setup, yet it does not save anything to it's DB do I need to add the "call compile preProcessFile "\iniDB\init.sqf";" still somewhere in the init.sqf ?

If so where exactly and what init.sqf ?

**Comment by Solo-** [comment]
And about those logs that some dont look at it, it's been going good for weeks pulling of off the main github page and all of a sudden it's no longer working that way with absolutely no info on the readme below it, so I assumed it was a working one that gone broken :)
