### ISSUE TITLE
Basesaving

### ISSUE THREAD

**Issue by Solo-** [JoSchaap/GoT_Wasteland_V2.Stratis#98]
Also, this server, I have iniDB setup, yet it does not save anything to it's DB do I need to add the "call compile preProcessFile "\iniDB\init.sqf";" still somewhere in the init.sqf ?

If so where exactly and what init.sqf ?

I  was assuming yet again the mission i pulled of the binary now it had iniDB into it's PBO as those folders and files about it are there.

**Comment by JoSchaap** [comment]
you need the iniDB mod

if i should rephrase the readme.txt -> https://github.com/JoSchaap/Arma3_Binary_PBO/blob/master/Sandbox56_GoT_Wasteland_V23_A3-Stratis/GoT_Readme.txt

or the comments in the settings file about inidb -> https://github.com/JoSchaap/Arma3_Binary_PBO/blob/master/Sandbox56_GoT_Wasteland_V23_A3-Stratis/GoT_Wasteland-config.sqf

let me know what/how so its more clear the next time :)
english is not my native language so im always open for tips on this :)

**Comment by Solo-** [comment]
Sorry to be so ignorant maybe, but there is no config-file ,  yes i see a config.sqf but that has nothing about it in anywhere, i also brwosed i think all init.sqf's i could find and also a no-go

**Comment by Solo-** [comment]
Just to be on the safe side here, i have the sanbox mission

**Comment by Solo-** [comment]
nvm, i am not used to use files outside the map... found it :(

**Comment by JoSchaap** [comment]
https://github.com/JoSchaap/Arma3_Binary_PBO/blob/master/Sandbox56_GoT_Wasteland_V23_A3-Stratis.zip?raw=true

that zip has it all :)
