### ISSUE TITLE
Tiny spawn bug

### ISSUE THREAD

**Issue by Solo-** [JoSchaap/GoT_Wasteland_V2.Stratis#99]
When you spawn at spartan near the lighthouse, you fall of a roof causing you to drain the health to 21%, I am sorry to not have a screenshot of it but i'm in the middle of doing something else :)

**Comment by Krunch** [comment]
That is true. First spawn ever on this new 2.3 version was at the lighthouse (east of the main island) and i spawned mid air.

**Comment by Solo-** [comment]
Same occurs at Isla Pythos, as well near the lighthouse

**Comment by JoSchaap** [comment]
this random 'advanturous spawn' is not intended and i will look into this :)

**Comment by JoSchaap** [comment]
seems this started hapenning since i've increased the radius for player spawns (you now spawn further outside towns)
i'll slighty decrease the radius again :+1:

**Comment by JoSchaap** [comment]
seems to no longer occur with: 656649dc6bfad71625725cef35ee58a24cc07501 and 0e2b5e909ce43302cbe53b8428afb1bc6da0dd72
